export const donationData = [
    {
      id: 1,
      title: "SNEHAVEEEDU - NSS",
      code: "#12345",
      account: "xxxx-xxxx-xxxx-xx34",
      goal: "25 Lakh",
      description: "We are planning to build a house for our friend. So, please add something you can afford.",
      accountHolder: "ABCDEF G",
      accountNumber: "XXXX-XXXX-XXXX-X620",
      ifscCode: "446543568345",
      branch: "NEW YORK",
      phone: "1234567890",
    },
    {
      id: 2,
      title: "NCC",
      code: "#56789",
      account: "xxxx-xxxx-xxxx-xx68",
      goal: "15 Lakh",
      description: "Supporting NCC students for educational purposes.",
      accountHolder: "HIJKLM N",
      accountNumber: "XXXX-XXXX-XXXX-X340",
      ifscCode: "768903456123",
      branch: "LOS ANGELES",
      phone: "0987654321",
    },
  ];